---
title: AI/MLbling About
baseURL: "https://aimlbling-about.ninerealmlabs.com/"
copyright: '<a rel="license" href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC-4.0</a>'

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: false # use /static/robots.txt

languageCode: en-US
defaultContentLanguage: "en"
timeZone: America/New_York
theme: hextra

outputs:
  home: [HTML]
  page: [HTML]
  section: [HTML, RSS]

module:
  hugoVersion:
    extended: true
    min: "0.112.0"
#
# services:
#   googleAnalytics:
#     ID: G-MEASUREMENT_ID
