---
baseURL: "https://aimlbling-about.ninerealmlabs.com/"
title: AI/MLbling About
# contentDir: /blog
copyright: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC-4.0</a>'

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: false # use /static/robots.txt

languageCode: en-us
defaultContentLanguage: "en"
timeZone: US/Eastern
theme: hextra
# services:
#   googleAnalytics:
#     ID: G-MEASUREMENT_ID
