---
baseURL: "https://aimlbling-about.ninerealmlabs.com/"
title: AI/MLbling About
subtitle:
  In which I organize my thoughts about LLMs, Generative AI, cool papers from arxiv.org, and other marginalia on topics
  in data science and machine learning.
colorScheme: auto
copyright: AI/MLbling About is licensed under CC BY-NC 4.0
enableEmoji: false
enableRobotsTXT: false # use /static/robots.txt
languageCode: en-us
defaultContentLanguage: "en"
katex: true
math: true
theme: hugo-coder
