---
goldmark:
  definitionList: true
  footnote: true
  linkify: true
  linkifyProtocol: https
  extensions:
    passthrough:
      delimiters:
        block:
          - - \[
            - \]
          - - $$
            - $$
        inline:
          - - \(
            - \)
          - - \$
            - \$
      enable: false
  strikethrough: true
  table: true
  taskList: true
  renderer:
    hardWraps: false # whether to replace newline characters within a paragraph with <br> elements.
    unsafe: true # whether to render raw HTML mixed within the Markdown
    # xhtml: false
  highlight:
    noClasses: false
