# Changes here will be overwritten by Copier
_commit: 2025.3.0-76-g45692f1
_src_path: gh:ninerealmlabs/precommit.template
conventional_commits: true
docker: true
editorconfig: true
markdown: true
prettier: true
python: true
shell: true
typos: true
yaml: true
