# Changes here will be overwritten by Copier
_commit: 2024.5.3
_src_path: gh:ninerealmlabs/precommit.template
editorconfig: true
hadolint: false
markdownlint: true
prettier: true
ruff: true
shellcheck: false
shfmt: false
typos: true
yamllint: true

