---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.6
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures
  - repo: local
    hooks:
      - id: forbid-yml
        name: Forbid .yml file extensions (use .yaml)
        entry: YAML file extension must be .yaml
        language: fail
        files: \.yml$
  - repo: local
    # repo: https://github.com/pre-commit/mirrors-prettier
    # rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: ""
        entry: bash -c "$HOME/.npm-packages/bin/prettier --write --ignore-unknown --no-error-on-unmatched-pattern"
        language: system
        # args:
        #   - --write
        #   - --ignore-unknown
        #   - --no-error-on-unmatched-pattern
        #   # - "--ignore-path '**/*.md'"
        #   # - "--ignore-path '**/*.y*ml'"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args:
          - --config=.markdownlint.yaml
          - --fix
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --config-file=.yamllint.yaml
          - --format=parsable
          - --strict
  - repo: https://github.com/petalmd/dockerfile-pre-commit
    rev: v1.0
    hooks:
      - id: dockerlint
        stages: [commit]
        # args: [--ignore, DL3025, --ignore, DL3018]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-x"]
        # ignore '*.zsh" scripts'
        exclude: "^.*zsh$"
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/crate-ci/typos
    rev: v1.20.10
    hooks:
      - id: typos
        args: [--config, .typos.toml]
        # exclude: "sops.yaml$"
        exclude: |
          (?x)^(
            ^.*(typos\.toml)$ |
            ^.*(\.sops\.yaml)$
          )$
