# --- project ----------------------------------------------------------------
[project]
name = "aimlbling-about"
version = "v0.beta"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = ["aiml", "pydantic>=2", "typing-extensions>=4.12"]

[dependency-groups]
dev = ["ipython>=8.8", "ipywidgets>=8.1.5", "notebook>=7.3.1"]
[project.urls]
Repository = "https://github.com/ahgraber/AIMLbling-about"

# --- uv ---------------------------------------------------------------------
# This file serves as the root pyproject.toml definition.
# The base project for the workspace is `./experiments/aiml`

[tool.uv]
package = false
default-groups = ["dev"]

[tool.uv.sources]
aiml = { workspace = true }
# aiml = { path = "./experiments/aiml" }

torch = [
  { index = "pytorch-cpu", marker = "platform_system != 'Darwin'" },
  # { index = "pytorch-gpu", extra="gpu", marker = "platform_system != 'Darwin'" },
]

[tool.uv.workspace]
members = ["./experiments/aiml"]
exclude = ["./docs", "./hugo", "./experiments/__pycache__", "./experiments/**/__pycache__"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
