---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Binaries
  PYTHON_BIN: python3
  HUGO_BIN: hugo
  # Directories
  CONTENT_DIR: "{{.ROOT_DIR}}/content"
  POSTS_DIR: "{{.CONTENT_DIR}}/posts"

includes:
  hugo: .taskfiles/hugo/taskfile.yaml

dotenv: [".env"]

# env:
#   ENVVAR: ''

tasks:
  default: task -l

  catchup:
    desc: Catch feature branch up to main
    interactive: true
    cmds:
      - git stash # save any work-in-progress
      - git fetch origin main # update remote
      # - git merge origin/main
      - git rebase origin/main
      - git push --force-with-lease
      - git stash pop # restore work-in-progress
