---
title: AI/MLbling About
baseURL: "https://aimlbling-about.ninerealmlabs.com/"
copyright: '<a rel="license" href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC-4.0</a>'

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: false # use /static/robots.txt

languageCode: en-US
defaultContentLanguage: "en"
timeZone: America/New_York
# theme: hextra # not needed with hugo modules

outputs:
  home: [HTML]
  page: [HTML]
  section: [HTML, RSS]

module:
  hugoVersion:
    extended: true
    min: "0.146.0"
  imports:
    - path: github.com/ahgraber/ai-treadmill
      mounts:
        - source: data/treadmill
          target: content/treadmill
          # Include all markdown files with their directory structure
          includeFiles: ["**/*.md", "**/*.jpeg", "**/*.png"]
    - path: github.com/imfing/hextra
#
# services:
#   googleAnalytics:
#     ID: G-MEASUREMENT_ID
