---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  CONTENT_DIR: "./content/"
  BLOG_DIR: "{{ .CONTENT_DIR }}/blog"
  EXPERIMENT_DIR: "./experiments/"

tasks:
  strip:
    desc: Strip metadata but leave outputs (ex. task jupyter:strip ipynb=./experiments/ragas/cost_analysis.ipynb)
    cmds:
      - nbstripout {{ .ipynb }} --keep-output
    requires:
      vars: ["ipynb"]
    preconditions:
      - {msg: "'nbstripout' not found (run 'pipx install nbstripout')", sh: "type nbstripout"}
      - {msg: "ipynb not found", sh: "test -f {{ .ipynb }}"}

  # strip-all:
  #   desc: strip metadata from all .ipynb files in dir
  #   cmds:
  #     - find . -name '*.ipynb' -exec nbstripout {} +
  #   preconditions:
  #     - {msg: "'nbstripout' not found (run 'pipx install nbstripout')", sh: "type nbstripout"}
