---
name: Build image, cache, and push to registry
description: Build image using docker buildx for multi-arch support

inputs:
  platforms:
    description: Image platform architectures
    required: true
  gh_registry:
    description: Github registry (ghcr.io/<owner>)
    required: true
  image_name:
    description: Image name
    required: true
  image_tag:
    description: Image tag
    required: true
  owner:
    description: Registry name
    required: true


outputs:
  image_digest:
    description: Image digest
    value: ${{ steps.build.outputs.digest }}

runs:
  using: composite
  steps:

    - name: Set up QEMU 🦤
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx 🐳
      id: buildx
      uses: docker/setup-buildx-action@v3

    ### https://github.com/docker/build-push-action
    ### https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md
    - name: Build image 🛠
      id: build
      uses: docker/build-push-action@v5
      with:
        builder: ${{ steps.buildx.outputs.name }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .  # explicitly include checked-out context with .git/ dir
        file: ./Dockerfile
        push: true
        tags: ${{ inputs.gh_registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}

    - name: Inspect image digest 🔬
      shell: bash
      run: |
        echo "IMAGE DIGEST: ${{ steps.build.outputs.digest }}"

    - name: Inspect new image 🔬
      shell: bash
      run: |
        docker pull ${{ inputs.gh_registry }}/${{ inputs.image_name }}@${{ steps.build.outputs.digest }}
